### ISSUE TITLE
可变长度问题

### ISSUE THREAD

**Issue by linzhi123** [qjadud1994/CRNN-Keras#10]
你好,你这个代码是只能识别长度为9的车牌吧?如果我想识别不固定长度的车牌,比如识别6,7,8这样长度的车牌时,代码应该怎么改?

**Comment by Heisenberg0391** [comment]
@linzhi123  小于最大序列长度的情况不用改，最大序列长度跟LSTM数量有关

**Comment by linzhi123** [comment]
我的意思是,比如我设置了最大长度为8,那么我输入的长度有5,6,7,但是代码会报错

**Comment by linzhi123** [comment]
> @linzhi123 小于最大序列长度的情况不用改，最大序列长度跟LSTM数量有关

我的意思是,比如我设置了最大长度为8,那么我输入的长度有5,6,7,但是代码会报错

**Comment by Heisenberg0391** [comment]
@linzhi123 他说要加padding

**Comment by linzhi123** [comment]
加padding??不懂耶 @Heisenberg0391

**Comment by Holmeyoung** [comment]
@linzhi123 就是不足8位的用0补齐
