### ISSUE TITLE
val_test

### ISSUE THREAD

**Issue by linzhi123** [qjadud1994/CRNN-Keras#11]
你好,请问test文件夹大概放几张测试图片?

**Comment by qjadud1994** [comment]
Please write in English.

**Comment by linzhi123** [comment]
Hello, how many test pictures are there in the test folder? @qjadud1994

**Comment by qjadud1994** [comment]
I do not remember how many copies I have.
But at that time I could not get real car license plate images, so I made synthetic car license plate image.
Therefore, the performance on synthetic car license plate images has been high, but the performance will be lower if the actual license plate photos are used.
