### ISSUE TITLE
Image Synthesis

### ISSUE THREAD

**Issue by azizsiyaev** [qjadud1994/CRNN-Keras#14]
. . .

**Comment by qjadud1994** [comment]
I emailed you.
Check it out.

**Comment by qjadud1994** [comment]
hello.

I will add to my github soon.

**Comment by quangvinh242003** [comment]
Hello,Thank you for your reply. However, can you share dataset now? Because I really need it nowThank you for your help

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 20, 2018 at 10:32, Beom<notifications@github.com> wrote:   hello.

I will add to my github soon.
