### ISSUE TITLE
ImageDataGenerator

### ISSUE THREAD

**Issue by soldierofhell** [qjadud1994/CRNN-Keras#16]
Has anyone succeed in modyfing standard keras_preprocessing.image.ImageDataGenerator class for this purpose? The TextImageGenerator() is fine to start, but if you want to utilize preprocessing functions it would be beneficial to use ImageDataGenerator?

**Comment by tuanphan09** [comment]
I implemented CRNN for captcha-recognition. That project's kind of like this one, I also used DataGenerator for fit_generator, so I think my repo would help
https://github.com/tuanphan09/captcha-recognition
