### ISSUE TITLE
do you get good result ever?

### ISSUE THREAD

**Issue by mengzhibin** [qjadud1994/CRNN-Keras#29]
I have seen another code about changing cnn feature to lstm as below 
`m = Permute((2, 1, 3), name='permute')(m)
m = TimeDistributed(Flatten(), name='timedistrib')(m)`
but yours is 
`    # CNN to RNN
    inner = Reshape(target_shape=((32, 2048)), name='reshape')(inner)  # (None, 32, 2048)
    inner = Dense(64, activation='relu', kernel_initializer='he_normal', name='dense1')(inner)  # (None, 32, 64)`
I think the reshape function is not correct, So could you tell if you have ever get good result?
thank you very much.

**Comment by tuanphan09** [comment]
I builded my model for captcha recognition base on his model and the result was pretty good.
You can vertify it in my project: 
https://github.com/tuanphan09/captcha-recognition

**Comment by bao-O** [comment]
@tuanphan09 Your project is amazing. I wanna train a model used for recognize license plate and have a question about dataset. I read that the input of this model has size 128*64 but my collected data has 
a variety of size and ratio. Can I use them for training this model? Does it effect to the accurate?

**Comment by tuanphan09** [comment]
Yes, you can.
You have to resize your dataset. It would effect the accurate a little but you can deal with it by data augmentation: shift, zoom, rotation,...Here is how you do it:
https://github.com/tuanphan09/captcha-recognition/blob/master/training.py#L44
