### ISSUE TITLE
prediction 결과가 이상합니다.

### ISSUE THREAD

**Issue by johojae** [qjadud1994/CRNN-Keras#38]
안녕하세요. 한국 분이신것 같아 한글로 적겠습니다.ㅎ

제가 올려주신 코드를 받아서 Text generator로 5개 타입에 대해 5000장 이미지를 트레이닝하고 1000장 이미지에 대해 원본 코드로 prediction 해보았는데요.

수행방법은 github에 있는 그대로 다른 부분은 수정하지 않았고 30번째 epochs의 결과값인 LSTM+BN5--30--17.991.hdf5를 Final_weight.hdf5 로 이름을 수정해서 prediction을 돌려봤더니 결과가 아래와 같습니다.
 올려주신 결과와는 많이 상이한데 제가 돌리면서 누락한 부분이 있을까요? 문제점을 아직 찾지 못해서 한 번 봐주시면 감사하겠습니다.
Predicted: 01라18  /  True: 서울 08아0188
Predicted: 1sk61  /  True: 서울 14나3841
Predicted: 4ek15  /  True: 서울 15수2594
Predicted: 광주 1eh82  /  True: 서울 17모8052
Predicted: 광주 1fj49  /  True: 서울 18허4839
Predicted: 전남 12마30  /  True: 서울 41아0634
Predicted: 4ek15  /  True: 서울 58모8149
Predicted: 4ek15  /  True: 서울 62나6864
Predicted: 05다15  /  True: 서울 64두9311
Predicted: 대전 5en19  /  True: 서울 80두1049
Predicted: 4ek15  /  True: 서울 80허8591

Predicted: 01라18  /  True: 서울 08아0188
Predicted: 1sk61  /  True: 서울 14나3841
Predicted: 4ek15  /  True: 서울 15수2594
Predicted: 광주 1eh82  /  True: 서울 17모8052
Predicted: 광주 1fj49  /  True: 서울 18허4839
Predicted: 전남 12마30  /  True: 서울 41아0634
Predicted: 4ek15  /  True: 서울 58모8149
Predicted: 4ek15  /  True: 서울 62나6864
Predicted: 05다15  /  True: 서울 64두9311
Predicted: 대전 5en19  /  True: 서울 80두1049
Predicted: 4ek15  /  True: 서울 80허8591
Predicted: 67아02  /  True: 서울 96거7915

**Comment by johojae** [comment]
추가로 트레이닝을 더 하였더니 개선이 되네요. 트레이닝이 부족한 문제였습니다.

**Comment by great-energizer** [comment]
> 추가로 트레이닝을 더 하였더니 개선이 되네요. 트레이닝이 부족한 문제였습니다.

학습 이미지와 Epoch은 어느 정도 추가해서 진행하신건가요?
