### ISSUE TITLE
ValueError: cannot copy sequence with size 7 to array axis with dimension 9

### ISSUE THREAD

**Issue by JustVugg** [qjadud1994/CRNN-Keras#45]
ValueError: cannot copy sequence with size 7 to array axis with dimension 9
Any help for this error?

**Comment by Zrufy** [comment]
I solve this problem adding space in file name until i have 9 characters.
Like "1234.jpg" in "1234     .jpg".
Maybe help!

**Comment by Papaass** [comment]
Hello Zrufy,

Can you the code you used to solved this problem ?

Best Regards
